[package]
name = "simple_api"
version = "0.1.0"
authors = ["FullGardenStudent"]
edition = "2018"


[dependencies]
actix-web = "3.3.2"
serde = "*"
diesel = { version = "1.4.6" ,features = ["postgres"]}
dotenv = "0.15.0"